CREATE TABLE EMP (
	EID INT,
	ENAME VARCHAR(50),
	DEPARTMENT VARCHAR(50),
	SALARY DECIMAL(8,2),
	JOININGDATE DATETIME,
	CITY VARCHAR(50) 
);
INSERT INTO EMP VALUES (101,'RAHUL','ADMIN',56000,'1990-1-1','RAJKOT')
INSERT INTO EMP VALUES (102,'Hardik','IT',18000,'1990-9-25','Ahmedabad')
INSERT INTO EMP VALUES (103,'Bhavin','HR',25000,'1991-5-14','Baroda')
INSERT INTO EMP VALUES (104,'Bhoomi','ADMIN',39000,'1991-2-8','RAJKOT')
INSERT INTO EMP VALUES (105,'Rohit','IT',17000,'1990-7-23','Jamnagar')
INSERT INTO EMP VALUES (106,'Priya','IT',9000,'1990-10-18','Ahmedabad')
INSERT INTO EMP VALUES (107,'Bhoomi','HR',34000,'1991-12-25','RAJKOT')


SELECT MAX(SALARY) AS MAX_SALARY,MIN(SALARY) AS MIN_SALARY FROM EMP
SELECT SUM(SALARY) AS TOTAL_SALARY, AVG(SALARY) AS AVG_SALARY FROM EMP
SELECT COUNT(EID) AS TOTAL_EMPLOYEE FROM EMP
SELECT MAX(SALARY) AS MAX_SALARY FROM EMP
WHERE CITY='RAJKOT'
SELECT MAX(SALARY) AS MAX_SALARY FROM EMP
WHERE DEPARTMENT='IT'
SELECT COUNT(EID) FROM EMP
WHERE JOININGDATE > '1991-2-8'
SELECT SUM(SALARY) FROM EMP
WHERE DEPARTMENT='HR'

SELECT AVG(SALARY) AS AVG_SALARY FROM EMP
WHERE DEPARTMENT='ADMIN'

SELECT SUM(SALARY) FROM EMP
WHERE DEPARTMENT='HR'

SELECT  COUNT(DISTINCT CITY) FROM EMP

SELECT COUNT(DISTINCT DEPARTMENT) FROM EMP

SELECT MIN(SALARY) FROM EMP
WHERE CITY='AHMEDABAD'

SELECT CITY, MAX(SALARY) FROM EMP
GROUP BY CITY

SELECT DEPARTMENT,MAX(SALARY) FROM EMP
GROUP BY DEPARTMENT

SELECT CITY,COUNT(EID) FROM EMP
GROUP BY CITY

SELECT DEPARTMENT,SUM(SALARY) AS TOTAL_SALARY FROM EMP
GROUP BY DEPARTMENT

SELECT AVG(SALARY) FROM EMP
GROUP BY DEPARTMENT

SELECT MAX(SALARY)-MIN(SALARY) AS DIFF FROM EMP



 
