create table SALES_DATA(

REGION VARCHAR(50),
PRODUCT VARCHAR(50),
SALES_AMOUNT INT,
ADATE DATE

);


INSERT INTO SALES_DATA VALUES('North America','WATCH',1500,'2023')
INSERT INTO SALES_DATA VALUES('Europe','Mobile',1200,'2023')
INSERT INTO SALES_DATA VALUES('Asia','WATCH',1800,'2023')
INSERT INTO SALES_DATA VALUES('North AMERICA','TV',900,'2024')
INSERT INTO SALES_DATA VALUES('Europe','WATCH',2000,'2024')
INSERT INTO SALES_DATA VALUES('Asia','Mobile',1000,'2024')
INSERT INTO SALES_DATA VALUES('North America','Mobile',1600,'2023')
INSERT INTO SALES_DATA VALUES('Europe','TV',1500,'2023')
INSERT INTO SALES_DATA VALUES('Asia','TV',1100,'2024')
INSERT INTO SALES_DATA VALUES('North America','WATCH',1700,'2024')

SELECT REGION,COUNT(SALES_AMOUNT) AS TOTAL FROM SALES_DATA
GROUP BY REGION

SELECT ADATE,AVG(SALES_AMOUNT) AS AVGSALES FROM SALES_DATA
GROUP BY PRODUCT

SELECT ADATE,MAX(SALES_AMOUNT) AS MAXSALES FROM SALES_DATA
GROUP BY ADATE

SELECT ADATE,REGION,MIN(SALES_AMOUNT) AS MINSALES FROM SALES_DATA
GROUP BY REGION,ADATE

SELECT REGION,COUNT(SALES_AMOUNT) AS TOTALSALES FROM SALES_DATA
GROUP BY REGION

SELECT SUM(SALES_AMOUNT),ADATE,PRODUCT FROM SALES_DATA
GROUP BY ADATE,PRODUCT

SELECT SUM(SALES_AMOUNT),REGION FROM SALES_DATA
GROUP BY REGION
HAVING SUM(SALES_AMOUNT)>5000


SELECT PRODUCT,SUM(SALES_AMOUNT) FROM SALES_DATA
GROUP BY PRODUCT
HAVING SUM(SALES_AMOUNT)<10000

SELECT ADATE,MAX(SALES_AMOUNT) FROM SALES_DATA
GROUP BY ADATE
HAVING MAX(SALES_AMOUNT)>500


SELECT REGION, COUNT(DISTINCT PRODUCT) FROM SALES_DATA
GROUP BY REGION
HAVING COUNT(DISTINCT PRODUCT)>3 

SELECT ADATE,MIN(SALES_AMOUNT) FROM SALES_DATA
GROUP BY ADATE
HAVING MIN(SALES_AMOUNT)<1000 


SELECT SUM(SALES_AMOUNT) AS TOTALAMOUNT,REGION FROM SALES_DATA
WHERE ADATE='2023'
GROUP BY REGION
ORDER BY SUM(SALES_AMOUNT)

------B------------
SELECT COUNT(SALES_AMOUNT),ADATE,REGION FROM SALES_DATA
GROUP BY ADATE,REGION
ORDER BY ADATE,REGION

select MAX(SALES_AMOUNT),REGION FROM SALES_DATA

GROUP BY REGION
HAVING MAX(SALES_AMOUNT)>1000


SELECT ADATE,SUM(SALES_AMOUNT) FROM SALES_DATA
GROUP BY ADATE
HAVING SUM(SALES_AMOUNT)>1000
ORDER BY ADATE DESC

SELECT TOP 3 REGION FROM SALES_DATA
WHERE ADATE='2024'

