USE CSE_3B_361
---------PART-A-------------

ALTER TABLE DEPOSIT 
ADD CITY VARCHAR(20),PINCODE INT
SELECT *FROM DEPOSIT

ALTER TABLE DEPOSIT 
ALTER COLUMN CNAME VARCHAR(35)

ALTER TABLE DEPOSIT
ALTER COLUMN CNAME INT

SP_RENAME 'DEPOSIT.ACOUNTNO' , 'ANO','COLUMN'
SELECT *FROM DEPOSIT

ALTER TABLE DEPOSIT
DROP COLUMN CITY
SELECT *FROM DEPOSIT;

SP_RENAME DEPOSIT ,DEPOSIT_DETAILS;

----------------PART-B-----------------------

SP_RENAME 'DEPOSIT_DETAILS.ADATE' , 'AOPENDATE','COLUMN'
SELECT *FROM DEPOSIT_DETAILS

ALTER TABLE DEPOSIT_DETAILS
DROP COLUMN AOPENDATE

SP_RENAME 'DEPOSIT_DETAILS.CNAME' , 'CUSTOMER_NAME','COLUMN'
SELECT *FROM DEPOSIT_DETAILS

----------------PART-C------------------------

CREATE TABLE STUDENT_DETAIL(
	Enrollment_No  VARCHAR (20),
	Name VARCHAR (25),
	CPI DECIMAL(5,2),
	BIRTHDATE DATETIME
);

ALTER TABLE STUDENT_DETAILS
ADD COLUMN City VARCHAR(20) NOT NULL,
ADD COLUMN Backlog INT NULL;

ALTER TABLE STUDENT_DETAILS
ALTER COLUMN NAME VARCHAR(35);




---------------------------------------------

CREATE TABLE DEPOSITE_DETAIL(
	ANO INT,
	CUSTOMER_NAME VARCHAR(35),
	BNAME VARCHAR(50),
	AMOUNT INT,
	PINCODE INT
);
--------------PART-A---------

DELETE 
FROM DEPOSIT_DETAILS
WHERE AMOUNT>=4000
SELECT *FROM DEPOSIT_DETAILS

DELETE DEPOSIT_DETAILS
WHERE BNAME='CHANDI'

DELETE DEPOSIT_DETAILS	
WHERE ANO>105

TRUNCATE TABLE DEPOSIT_DETAILS

DROP TABLE DEPOSIT_DETAILS

---------------PART-B-------------------

CREATE TABLE EMPLOYEE_MASTER(
	EMPNO INT,
	EMPNAME VARCHAR(25),
	JOININGDATE DATETIME,
	SALARY DECIMAL(8,2),
	CITY VARCHAR(20)
);

INSERT INTO EMPLOYEE_MASTER VALUES(101,'KEYUR','02-1-5',120000,'RAJKOT'),(102,'HARDIK','04-2-15',140000,'AHEMDABD'),
(104,'BHOOMI','06-3-14',150000,'BARODA'),(105,'HARMIT','04-2-04',140000,'RAJKOT'),
(106,'MITESH','01-9-25',5000,'JAMNAGAR'),(107,'MEERA',NULL,7000,'MORBI'),(108,'KISHAN','03-2-6',1000,NULL);
SELECT *FROM EMPLOYEE_MASTER

DELETE 
FROM EMPLOYEE_MASTER
WHERE SALARY>=14000

DELETE 
FROM EMPLOYEE_MASTER
WHERE CITY='RAJKOT'

DELETE 
FROM EMPLOYEE_MASTER
WHERE JOININGDATE>'07-1-1'

DELETE
FROM EMPLOYEE_MASTER
WHERE JOININGDATE IS NULL 
AND EMPNAME IS NOT NULL

DELETE FROM EMPLOYEE_MASTER
WHERE SALARY = 10000;

DELETE FROM EMPLOYEE_MASTER
WHERE CITY IS NOT NULL AND CITY != '';

TRUNCATE TABLE EMPLOYEE_MASTER

DROP TABLE EMPLOYEE_MASTER





